# Generated by Django 5.0.3 on 2024-04-19 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='name',
            new_name='doc_name',
        ),
    ]
