# Generated by Django 5.0.3 on 2024-04-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_rename_name_document_doc_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='id',
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='software',
            name='license',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
