# Generated by Django 5.0.3 on 2024-04-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_remove_software_id_alter_document_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='software',
            name='license',
            field=models.IntegerField(default=234657392, primary_key=True, serialize=False),
        ),
    ]
