# Generated by Django 5.0.3 on 2024-04-23 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0005_alter_software_license'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='date_created',
            field=models.DateTimeField(default='2004-06-20'),
        ),
        migrations.AddField(
            model_name='software',
            name='id',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
