# Generated by Django 5.0.3 on 2024-04-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0007_alter_software_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.RemoveField(
            model_name='software',
            name='id',
        ),
        migrations.AddField(
            model_name='software',
            name='id',
            field=models.BigAutoField(auto_created=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software',
            name='owner',
            field=models.CharField(default='admin', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='software',
            name='license',
            field=models.IntegerField(default=345698764),
        ),
    ]
