# Generated by Django 5.0.3 on 2024-04-25 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0008_delete_document_remove_software_user_software_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='date_created',
        ),
        migrations.AddField(
            model_name='software',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='software',
            name='license',
            field=models.IntegerField(default=123456789),
        ),
    ]
