# Generated by Django 5.0.3 on 2024-04-25 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0009_remove_software_date_created_software_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='s_accessible_by_all',
            field=models.BooleanField(default=False, verbose_name='Accessible by all users'),
        ),
        migrations.AlterField(
            model_name='software',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='software',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Allowed users'),
        ),
    ]
