# Generated by Django 5.0.3 on 2024-04-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0010_software_s_accessible_by_all_alter_software_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='id',
        ),
        migrations.AddField(
            model_name='software',
            name='id_id',
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
